### PR TITLE
fix: refactor imports for dbt 1.8.0+

### PR DESCRIPTION
**Pull request by ryan-pip**
Fix import paths for dbt common and adapter components for dbt 1.8.0.

### CODE REVIEW

**Comment by syou6162** [comment]
@ryan-pip Can you pull the latest from the main branch and add dbt 1.8 to the test?

- https://github.com/z3z1ma/dbt-osmosis/pull/150/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR14

The reason for this addition is to make sure that this pull request works correctly with dbt 1.8 and that dbt 1.7 and below also work fine. FYI @z3z1ma

**Comment by ryan-pip** [comment]
Did you want me to add dbt-version 1.8.0 to the versions that will be tested as well?

**Comment by syou6162** [comment]
@ryan-pip Yes, I would like you to do so, and to ensure that dbt-osmosis works with multiple dbt-core versions, we would like to add 1.8.0 to our test subject. This would make dbt-osmosis more maintainable.

**Comment by ryan-pip** [comment]
@syou6162, Tests have been added and are passing. Anything else needed here?

**Comment by syou6162** [comment]
@ryan-pip Thanks for adding the test! 

@z3z1ma We have confirmed on CI that it works fine with 1.8 and versions prior to 1.7, so it looked good. Could you please review it?

**Review by syou6162 — APPROVED** [review]

**Comment by z3z1ma** [comment]
LGTM thanks, I will cut a new release on PyPI and get the changelog, readme, and docs site updated.

**Comment by FrankTub** [comment]
@z3z1ma , when can we expect a new version?

**Pull request merged**
